In [1]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_csv('recife-2021.CSV', delimiter=';', skiprows=8, encoding='latin1')

In [5]:
df_reduzido = df.dropna(subset=['RADIACAO GLOBAL (Kj/m²)'])
df_reduzido

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
9,2021/01/01,0900 UTC,0,1013,1013,"1012,6","114,6","25,1","22,1","25,1","24,3","22,1","21,6",86.0,83.0,83.0,116.0,"3,5","1,1",NaN
10,2021/01/01,1000 UTC,0,"1013,3","1013,3",1013,"762,2","27,2","21,4","27,5","25,1","22,3","21,2",83.0,69.0,71.0,109.0,"4,8","1,7",NaN
11,2021/01/01,1100 UTC,0,"1013,5","1013,6","1013,3","1862,8","28,8","20,9","28,9","27,2","22,3","20,7",72.0,62.0,63.0,124.0,"5,1","2,1",NaN
12,2021/01/01,1200 UTC,0,"1013,6","1013,7","1013,4","2543,3","29,6","21,4","29,6","28,7","21,6","20,4",63.0,59.0,61.0,122.0,"6,4","2,3",NaN
13,2021/01/01,1300 UTC,0,"1013,6","1013,7","1013,5","3397,4","30,3","20,9","30,5","29,7","21,5","20,3",61.0,55.0,57.0,131.0,"6,5","2,5",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7553,2021/11/11,1700 UTC,0,"1011,4","1011,8","1011,4","2262,6","30,3",23,"31,1","30,1","23,7","22,2",66.0,60.0,65.0,121.0,"6,5","2,5",NaN
7554,2021/11/11,1800 UTC,0,"1011,1","1011,4",1011,"1948,9","29,4","22,6",31,"29,4","23,4","22,4",68.0,60.0,67.0,118.0,"6,2","2,7",NaN
7555,2021/11/11,1900 UTC,0,1011,"1011,1","1010,9","1019,7","28,6","22,6",30,"28,5","23,3","22,3",72.0,66.0,70.0,129.0,"6,2",2,NaN
7556,2021/11/11,2000 UTC,0,"1011,2","1011,3",1011,"287,3","27,4","22,6","28,7","27,4","22,7","22,3",75.0,69.0,75.0,107.0,"5,8","1,9",NaN
7557,2021/11/11,2100 UTC,0,"1011,7","1011,7","1011,2",9,"26,8","22,7","27,4","26,8","22,8","22,5",79.0,75.0,78.0,120.0,"4,9","1,6",NaN

In [6]:
nulos_antes = df['RADIACAO GLOBAL (Kj/m²)'].isnull().sum()
print("Quantidade de nulos antes da remoçao: ",nulos_antes)

Quantidade de nulos antes da remoçao:  4644

In [7]:
nulos_depois = df_reduzido['RADIACAO GLOBAL (Kj/m²)'].isnull().sum()
print("Quantidade de nulos depois da remoçao: ",nulos_depois)

Quantidade de nulos depois da remoçao:  0

In [8]:
df_reduzido = df[['Data', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'RADIACAO GLOBAL (Kj/m²)' ]].sample(n=1000)
df_reduzido.head(1000)

,Data,TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),RADIACAO GLOBAL (Kj/m²)
8542,2021/12/22,NaN,NaN
3271,2021/05/17,22,NaN
2545,2021/04/17,"24,2",NaN
6070,2021/09/10,"25,1",NaN
1714,2021/03/13,"26,3","393,4"
...,...,...,...
5306,2021/08/10,"22,2",NaN
7967,2021/11/28,NaN,NaN
5394,2021/08/13,"27,9","2375,1"
294,2021/01/13,"23,4",NaN
7034,2021/10/21,"26,6",NaN

In [9]:
df_reduzido['TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)'].dtype

dtype('O')

In [11]:
df_reduzido = pd.to_numeric(df_reduzido['TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)'], errors='coerce')