## Dados utilizados da cidade do Rio de Janeiro do Forte de Copacabana no ano 2023

In [1]:
import pandas as pd

df = pd.read_csv('RIO-DE-JANEIRO_FORTE-DE-COPACABANA_2023.csv', delimiter=';', skiprows=8, encoding='latin1')

In [2]:
df.columns

Index(['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)',
       'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
       'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)',
       'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)',
       'RADIACAO GLOBAL (Kj/m²)',
       'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
       'TEMPERATURA DO PONTO DE ORVALHO (°C)',
       'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)',
       'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)',
       'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)',
       'UMIDADE RELATIVA DO AR, HORARIA (%)',
       'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)',
       'VENTO, VELOCIDADE HORARIA (m/s)', 'Unnamed: 19'],
      dtype='object')

**1. Calcular a média da temperatura da amostra**

In [3]:
print(df['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].dtype)

object

In [7]:
df['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'] = pd.to_numeric(df['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'], errors='coerce')

media = df['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].mean()
print(f"A média da temperatura é de {media:.2f}°C.")

A média da temperatura é de 24.15°C.

**2. Retirar nulos da coluna 'RADIACAO GLOBAL (Kj/m²)'**

In [13]:
df_sem_nulos_coluna = df.dropna(subset=['RADIACAO GLOBAL (Kj/m²)'])
df_sem_nulos_coluna

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
9,2023/01/01,0900 UTC,0,"1010,2","1010,2","1009,2","124,6",23.0,NaN,"23,2","22,7",NaN,NaN,NaN,NaN,NaN,266.0,"3,3",1,NaN
10,2023/01/01,1000 UTC,0,"1010,9","1010,9","1010,2","887,1",24.0,NaN,"24,2","22,9",NaN,NaN,NaN,NaN,NaN,226.0,"2,5","1,1",NaN
11,2023/01/01,1100 UTC,0,"1011,1","1011,2","1010,9","1533,7",NaN,"26,2","26,3","23,7",NaN,NaN,NaN,NaN,99.0,100.0,"1,9",",9",NaN
12,2023/01/01,1200 UTC,0,"1011,6","1011,6","1011,1","1983,3",NaN,"20,5","26,5","24,2",26,20,99.0,77.0,79.0,254.0,3,"1,7",NaN
13,2023/01/01,1300 UTC,0,"1011,5","1011,6","1011,5","3094,8",NaN,"21,1","27,8","24,2","22,7","20,2",79.0,68.0,68.0,161.0,3,"1,5",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,2023/12/31,1800 UTC,0,"1011,6",1012,"1011,6","1133,5",NaN,"20,8","25,7","24,6","21,6","20,6",83.0,75.0,79.0,88.0,"3,2","1,3",NaN
8755,2023/12/31,1900 UTC,0,1011,"1011,6",1011,749,NaN,"21,1","25,1","24,4","21,3","20,6",82.0,78.0,82.0,63.0,"3,5","1,3",NaN
8756,2023/12/31,2000 UTC,",2","1010,8","1011,1","1010,7","470,2",NaN,"20,7","24,6","23,8","21,4","20,5",83.0,81.0,83.0,95.0,"6,3","4,5",NaN
8757,2023/12/31,2100 UTC,0,1011,1011,"1010,8","142,1",NaN,"20,9","23,8","23,3","21,1","20,6",87.0,82.0,86.0,100.0,"6,5","5,1",NaN
8758,2023/12/31,2200 UTC,0,"1011,7","1011,7",1011,"20,7",NaN,"21,3","23,3",23,"21,3","20,7",90.0,86.0,90.0,82.0,"6,7","4,1",NaN

**3. Copiar o dataframe reduzindo para 3 colunas e 1000 linhas aleatórias**

In [21]:
# Selecionar colunas específicas
df_reduzido = df[['Data', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, VELOCIDADE HORARIA (m/s)']]

df_reduzido.head()

,Data,"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2023/01/01,67.0,2
1,2023/01/01,80.0,1
2,2023/01/01,NaN,"1,3"
3,2023/01/01,NaN,"1,4"
4,2023/01/01,NaN,",6"

In [23]:
# Selecionar 1000 linhas aleatórias
df_reduzido = df_reduzido.sample(n=1000, random_state=42)

df_reduzido

,Data,"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, VELOCIDADE HORARIA (m/s)"
8046,2023/12/02,NaN,",7"
3910,2023/06/12,NaN,3
411,2023/01/18,78.0,"1,2"
3146,2023/05/12,70.0,"1,1"
8664,2023/12/28,82.0,"1,3"
...,...,...,...
6152,2023/09/14,37.0,"4,8"
7550,2023/11/11,NaN,"4,6"
8476,2023/12/20,96.0,",8"
828,2023/02/04,67.0,"1,6"
6266,2023/09/19,NaN,"1,7"

#### **Bônus I: Normalizar uma coluna**

#### Coluna usada: 'UMIDADE RELATIVA DO AR, HORARIA (%)'

In [24]:
df['Coluna_normalizada'] = (df['UMIDADE RELATIVA DO AR, HORARIA (%)'] - df['UMIDADE RELATIVA DO AR, HORARIA (%)'].min()) / (df['UMIDADE RELATIVA DO AR, HORARIA (%)'].max() - df['UMIDADE RELATIVA DO AR, HORARIA (%)'].min())
df['Coluna_normalizada']

0       0.625000
1       0.772727
2            NaN
3            NaN
4            NaN
          ...
8755    0.795455
8756    0.806818
8757    0.840909
8758    0.886364
8759    0.829545
Name: Coluna_normalizada, Length: 8760, dtype: float64

#### **Bônus II: Outra forma de processamento de dados**

#### Filtrar linhas com base em condições:

Coluna usada: 'VENTO, VELOCIDADE HORARIA (m/s)'

In [39]:
df['VENTO, VELOCIDADE HORARIA (m/s)'] = pd.to_numeric(df['VENTO, VELOCIDADE HORARIA (m/s)'], errors='coerce')

filtrado = df[df['VENTO, VELOCIDADE HORARIA (m/s)'] > 2]
filtrado

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),...,TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19,Coluna_normalizada
39,2023/01/02,1500 UTC,0,"1007,9","1008,9","1007,9","3957,9",NaN,"20,1","28,7",...,21,"19,5",65.0,60.0,62.0,76.0,"5,2",3.0,NaN,0.568182
81,2023/01/04,0900 UTC,0,"1002,5","1002,5","1002,3","54,1",NaN,"16,9","29,5",...,"17,5","16,9",54.0,47.0,47.0,335.0,"8,7",3.0,NaN,0.397727
96,2023/01/05,0000 UTC,0,"1005,9","1005,9","1005,8",NaN,NaN,NaN,"23,5",...,NaN,NaN,NaN,NaN,NaN,267.0,"6,7",3.0,NaN,NaN
101,2023/01/05,0500 UTC,0,"1004,8","1005,3","1004,7",NaN,NaN,NaN,"22,4",...,NaN,NaN,NaN,NaN,NaN,263.0,7,3.0,NaN,NaN
115,2023/01/05,1900 UTC,0,"1006,3","1006,7","1006,2","282,9",NaN,NaN,22,...,NaN,NaN,NaN,NaN,NaN,266.0,"10,9",4.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8657,2023/12/27,1700 UTC,0,"1012,3","1012,8","1012,3","3032,5",NaN,"21,3","28,4",...,"22,6","21,2",77.0,69.0,76.0,251.0,"6,3",3.0,NaN,0.727273
8659,2023/12/27,1900 UTC,0,"1011,8","1012,1","1011,8","2361,8",NaN,"21,9","27,3",...,"22,4","21,6",78.0,73.0,77.0,245.0,"6,7",3.0,NaN,0.738636
8685,2023/12/28,2100 UTC,0,"1008,1","1008,4",1008,"175,8",NaN,"21,8","25,1",...,"21,8","21,4",85.0,81.0,85.0,95.0,"9,8",7.0,NaN,0.829545
8728,2023/12/30,1600 UTC,0,"1009,4","1009,4","1008,8","1026,5",NaN,"23,7","26,2",...,"23,9","23,2",92.0,84.0,92.0,262.0,"8,5",4.0,NaN,0.909091
8733,2023/12/30,2100 UTC,0,"1010,4","1010,4","1009,8","112,9",NaN,"21,7","23,9",...,"22,3","21,7",92.0,89.0,91.0,262.0,"7,8",3.0,NaN,0.897727