In [1]:
import pandas as pd
import numpy as np

 - calcular a média da temperatura da amostra
    - retirar nulos da coluna 'RADIACAO GLOBAL (Kj/m2)'
    - copiar o dataframe reduzindo para 3 colunas (a sua escolha) e 1000 linhas (aleatórias)
    - Bônus: normalizar coluna (qualquer uma)
    - Bônus II: pesquisar sobre outras formas de processamento de dados além das vistas em sala de aula

In [3]:
#ler o arquivo
df= pd.read_csv('recife-2021.CSV', delimiter=';', skiprows=8, encoding='latin1')

In [70]:
df.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2021/01/01,0000 UTC,0,"1013,2","1013,2","1012,9",NaN,"26,1","21,8","26,5","26,1","21,9","21,5",77.0,75.0,77.0,115.0,"5,7","1,4",NaN
1,2021/01/01,0100 UTC,0,"1013,3","1013,4","1013,2",NaN,"25,9","22,1","26,1","25,9","22,1","21,7",79.0,77.0,79.0,106.0,"4,1","1,3",NaN
2,2021/01/01,0200 UTC,0,"1012,8","1013,3","1012,8",NaN,"25,6",22,26,"25,6","22,2",22,81.0,79.0,81.0,111.0,"4,4",",9",NaN
3,2021/01/01,0300 UTC,"1,2","1012,5","1012,8","1012,5",NaN,"24,6","22,5","25,6","24,6","22,5",22,88.0,81.0,88.0,110.0,"3,4","1,2",NaN
4,2021/01/01,0400 UTC,0,"1011,8","1012,5","1011,8",NaN,"24,5","22,7","24,7","24,4","22,7","22,5",90.0,88.0,90.0,119.0,"3,4",",8",NaN

In [77]:
#Retirar nulos da coluna Temperatura do ar
df_reduzidot = df.dropna(subset=['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'])
df_reduzidot

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2021/01/01,0000 UTC,0,"1013,2","1013,2","1012,9",NaN,"26,1","21,8","26,5","26,1","21,9","21,5",77.0,75.0,77.0,115.0,"5,7","1,4",NaN
1,2021/01/01,0100 UTC,0,"1013,3","1013,4","1013,2",NaN,"25,9","22,1","26,1","25,9","22,1","21,7",79.0,77.0,79.0,106.0,"4,1","1,3",NaN
2,2021/01/01,0200 UTC,0,"1012,8","1013,3","1012,8",NaN,"25,6",22,26,"25,6","22,2",22,81.0,79.0,81.0,111.0,"4,4",",9",NaN
3,2021/01/01,0300 UTC,"1,2","1012,5","1012,8","1012,5",NaN,"24,6","22,5","25,6","24,6","22,5",22,88.0,81.0,88.0,110.0,"3,4","1,2",NaN
4,2021/01/01,0400 UTC,0,"1011,8","1012,5","1011,8",NaN,"24,5","22,7","24,7","24,4","22,7","22,5",90.0,88.0,90.0,119.0,"3,4",",8",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7562,2021/11/12,0200 UTC,0,"1011,9","1012,6","1011,9",NaN,"24,9","23,3","25,6","24,9","23,3","22,9",91.0,85.0,91.0,213.0,2,",4",NaN
7563,2021/11/12,0300 UTC,0,"1011,2","1011,9","1011,2",NaN,"24,6","23,5","24,9","24,5","23,5","23,2",94.0,91.0,94.0,230.0,"1,2",",3",NaN
7564,2021/11/12,0400 UTC,",6","1010,7","1011,2","1010,7",NaN,"24,2","23,5","24,8","24,2","23,9","23,5",96.0,94.0,96.0,286.0,"1,7",",4",NaN
7565,2021/11/12,0500 UTC,",2","1010,2","1010,7","1010,2",NaN,"24,1","23,7","24,2","24,1","23,7","23,5",98.0,96.0,98.0,277.0,"1,1",",4",NaN
7566,2021/11/12,0600 UTC,",2","1010,1","1010,2",1010,NaN,"24,3","24,1","24,3","23,9","24,1","23,6",99.0,97.0,99.0,196.0,"1,5",",7",NaN

In [78]:
df_reduzidot = pd.to_numeric(df_reduzidot['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'], errors='coerce')
df_reduzidot

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
7562   NaN
7563   NaN
7564   NaN
7565   NaN
7566   NaN
Name: TEMPERATURA DO AR - BULBO SECO, HORARIA (°C), Length: 7551, dtype: float64

In [4]:
#Retirar nulos da coluna RADIACAO GLOBAL
df_reduzido = df.dropna(subset=['RADIACAO GLOBAL (Kj/m²)'])
df_reduzido

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
9,2021/01/01,0900 UTC,0,1013,1013,"1012,6","114,6","25,1","22,1","25,1","24,3","22,1","21,6",86.0,83.0,83.0,116.0,"3,5","1,1",NaN
10,2021/01/01,1000 UTC,0,"1013,3","1013,3",1013,"762,2","27,2","21,4","27,5","25,1","22,3","21,2",83.0,69.0,71.0,109.0,"4,8","1,7",NaN
11,2021/01/01,1100 UTC,0,"1013,5","1013,6","1013,3","1862,8","28,8","20,9","28,9","27,2","22,3","20,7",72.0,62.0,63.0,124.0,"5,1","2,1",NaN
12,2021/01/01,1200 UTC,0,"1013,6","1013,7","1013,4","2543,3","29,6","21,4","29,6","28,7","21,6","20,4",63.0,59.0,61.0,122.0,"6,4","2,3",NaN
13,2021/01/01,1300 UTC,0,"1013,6","1013,7","1013,5","3397,4","30,3","20,9","30,5","29,7","21,5","20,3",61.0,55.0,57.0,131.0,"6,5","2,5",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7553,2021/11/11,1700 UTC,0,"1011,4","1011,8","1011,4","2262,6","30,3",23,"31,1","30,1","23,7","22,2",66.0,60.0,65.0,121.0,"6,5","2,5",NaN
7554,2021/11/11,1800 UTC,0,"1011,1","1011,4",1011,"1948,9","29,4","22,6",31,"29,4","23,4","22,4",68.0,60.0,67.0,118.0,"6,2","2,7",NaN
7555,2021/11/11,1900 UTC,0,1011,"1011,1","1010,9","1019,7","28,6","22,6",30,"28,5","23,3","22,3",72.0,66.0,70.0,129.0,"6,2",2,NaN
7556,2021/11/11,2000 UTC,0,"1011,2","1011,3",1011,"287,3","27,4","22,6","28,7","27,4","22,7","22,3",75.0,69.0,75.0,107.0,"5,8","1,9",NaN
7557,2021/11/11,2100 UTC,0,"1011,7","1011,7","1011,2",9,"26,8","22,7","27,4","26,8","22,8","22,5",79.0,75.0,78.0,120.0,"4,9","1,6",NaN

In [5]:
#Quantidade de nulos antes
nulos_antes = df['RADIACAO GLOBAL (Kj/m²)'].isnull().sum()
print("Quantidade de nulos antes da remoçao: ",nulos_antes)

Quantidade de nulos antes da remoçao:  4644

In [6]:
#Quantidade de nulos depois da remoçao
nulos_depois = df_reduzido['RADIACAO GLOBAL (Kj/m²)'].isnull().sum()
print("Quantidade de nulos depois da remoçao: ",nulos_depois)

Quantidade de nulos depois da remoçao:  0

In [7]:
#reduzindo para 3 colunas e 1000 linhas (aleatórias) 
df_reduzido = df[['Data', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)' ]].sample(n=1000)
df_reduzido.head(1000)

,Data,TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)"
6306,2021/09/20,"29,1","27,2"
5515,2021/08/18,"26,5","24,8"
4781,2021/07/19,"21,8","21,6"
7255,2021/10/30,21,"20,5"
8141,2021/12/06,NaN,NaN
...,...,...,...
2728,2021/04/24,"31,2","30,5"
4749,2021/07/17,"23,6","23,2"
1096,2021/02/15,"27,9","26,6"
527,2021/01/22,"26,7","26,4"
2059,2021/03/27,28,"27,2"