In [134]:
import pandas as pd
import numpy as np

df_cdba = pd.read_csv('importar/CARTEIRADIARIA_CDBA_1408.csv', delimiter=';', encoding='latin1')
df_cdneos = pd.read_csv('importar/CARTEIRADIARIA_CDNEOS_1408.csv', delimiter=';', encoding='latin1')
df_cdpe = pd.read_csv('importar/CARTEIRADIARIA_CDPE_1408.csv', delimiter=';', encoding='latin1')
df_cdrn = pd.read_csv('importar/CARTEIRADIARIA_RN_1408.csv', delimiter=';', encoding='latin1')

In [132]:

df_cdba = (df_cdba[['Cliente','Código','Cotação','Quantidade Total']].dropna(axis=0))
df_cdneos = (df_cdneos[['Cliente','Código','Cotação','Quantidade Total']].dropna(axis=0))
df_cdpe = (df_cdpe[['Cliente','Código','Cotação','Quantidade Total']].dropna(axis=0))
df_cdrn = (df_cdrn[['Cliente','Código','Cotação','Quantidade Total']].dropna(axis=0))

In [133]:
df = pd.concat([df_cdba,df_cdneos,df_cdpe,df_cdrn]).reset_index(drop='True') #axis = 0 -> linhas
df

            Cliente    Código          Cotação      Quantidade Total
0   CUST0207         CUST0970      25,82869639    7.028.168,01954160
1   CUST0207         CUST1190       2,23259433  146.839.413,35566800
2   CUST0207         CUST1192       2,36069502   42.314.229,24087930
3   CUST0207         CUST2315       1,10598782   22.048.514,13859530
4   CUST0207         CUST3075       1,20126644   73.961.661,22542130
5   CUST0207         CUST3081       1,11953438   72.716.409,24649740
6   CUST0207         TCUS0349  13.268,40421089          223,67755270
7   CUST0207         TCUS0646  16.858,34032199          243,13447753
8   CUST0207         TFBR0308       1,57914690    7.274.663,39078412
9   CUST0207         TFBT0875       1,30131880    7.756.702,34152928
10  CUST0207         TFGE0014  16.858,34032199          522,04050064
11  CUST0207         TFML2226       2,25605384   15.955.103,10631320
12  CUST1903         CUST0970      25,82869639    7.848.954,24687267
13  CUST1903         CUST1190       2,23259433  225.030.148,93302700
14  CUST1903         CUST1192       2,36069502   50.177.362,42986940
15  CUST1903         CUST2315       1,10598782   24.027.278,33403740
16  CUST1903         CUST3075       1,20126644   84.324.116,26935590
17  CUST1903         CUST3081       1,11953438   47.217.366,52051970
18  CUST1903         TCUS0349  13.268,40421089           27,57166332
19  CUST1903         TCUS0646  16.858,34032199           87,22475847
20  CUST1903         TFBR0308       1,57914690    5.604.180,00468030
21  CUST1903         TFBR0354     119,24225850       56.174,81475307
22  CUST1903         TFBT0875       1,30131880      956.131,63849146
23  CUST1903         TFGE0014  16.858,34032199            7,09019401
24  CUST1903         TFML2226       2,25605384   15.539.222,66138480
25  CUST0388         CUST1190       2,23259433    4.767.306,13295637
26  CUST0388         CUST1192       2,36069502      820.745,25562894
27  CUST0388         CUST2315       1,10598782    4.981.962,98233473
28  CUST0388         TFBR0308       1,57914690      193.662,58301219
29  CUST0388         TFML2226       2,25605384      333.917,39314836
30  CUST0347         CUST1190       2,23259433   15.716.349,24312460
31  CUST0347         CUST1192       2,36069502    1.396.101,25480191
32  CUST0347         CUST2315       1,10598782    3.940.233,93303525
33  CUST0347         TFBR0308       1,57914690      144.389,06923798
34  CUST0347         TFBR0354     119,24225850       43.825,18524693
35  CUST0347         TFML2226       2,25605384      168.144,65764676

In [130]:
concatenar_colunas = pd.concat([df_cdba,df_cdneos],axis=1) #concatena colunas (axis=1)
concatenar_colunas #concatena pelo index

,Cliente,Código,Cotação,Quantidade Total,Cliente,Código,Cotação,Quantidade Total
0,CUST0207,CUST0970,"25,82869639","7.028.168,01954160",CUST1903,CUST0970,"25,82869639","7.848.954,24687267"
1,CUST0207,CUST1190,"2,23259433","146.839.413,35566800",CUST1903,CUST1190,"2,23259433","225.030.148,93302700"
2,CUST0207,CUST1192,"2,36069502","42.314.229,24087930",CUST1903,CUST1192,"2,36069502","50.177.362,42986940"
3,CUST0207,CUST2315,"1,10598782","22.048.514,13859530",CUST1903,CUST2315,"1,10598782","24.027.278,33403740"
4,CUST0207,CUST3075,"1,20126644","73.961.661,22542130",CUST1903,CUST3075,"1,20126644","84.324.116,26935590"
5,CUST0207,CUST3081,"1,11953438","72.716.409,24649740",CUST1903,CUST3081,"1,11953438","47.217.366,52051970"
6,CUST0207,TCUS0349,"13.268,40421089","223,67755270",CUST1903,TCUS0349,"13.268,40421089","27,57166332"
7,CUST0207,TCUS0646,"16.858,34032199","243,13447753",CUST1903,TCUS0646,"16.858,34032199","87,22475847"
8,CUST0207,TFBR0308,"1,57914690","7.274.663,39078412",CUST1903,TFBR0308,"1,57914690","5.604.180,00468030"
9,CUST0207,TFBT0875,"1,30131880","7.756.702,34152928",CUST1903,TFBR0354,"119,24225850","56.174,81475307"
10,CUST0207,TFGE0014,"16.858,34032199","522,04050064",CUST1903,TFBT0875,"1,30131880","956.131,63849146"
11,CUST0207,TFML2226,"2,25605384","15.955.103,10631320",CUST1903,TFGE0014,"16.858,34032199","7,09019401"
12,NaN,NaN,NaN,NaN,CUST1903,TFML2226,"2,25605384","15.539.222,66138480"