In [12]:
import pandas as pd

df = pd.read_csv('brasilia_2020.csv', delimiter=';', skiprows=8, encoding='latin1')

In [26]:
df_amostra = df.sample(n=20)

In [27]:
df_amostra.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
7995,2020/11/29,0300 UTC,0,"888,7","889,3","888,7",NaN,"20,2","13,1","20,9","20,1","13,5",13,64,62.0,64,99,"5,2","2,7",NaN
7648,2020/11/14,1600 UTC,0,"886,1","886,8","886,1","1014,9",23,"17,7","24,4","22,4","19,4","16,4",79,63.0,72,285,"6,5",2,NaN
4298,2020/06/28,0200 UTC,0,"888,7","888,7","888,6",NaN,"17,1","12,3","17,2","16,4","12,3","11,5",74,72.0,74,153,"1,4",",6",NaN
3197,2020/05/13,0500 UTC,0,"887,6","888,1","887,6",NaN,"17,4","14,8",18,"17,2","15,1","14,4",86,81.0,84,90,"3,5","1,7",NaN
4297,2020/06/28,0100 UTC,0,"888,6","888,6","888,4",NaN,"16,6",12,"17,2","16,4","12,1","11,6",75,71.0,74,136,"1,7","1,1",NaN

In [15]:
f_amostra = df_amostra[['Data', 'Hora UTC', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)']]

In [16]:
df_amostra

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
1562,2020/03/06,0200 UTC,0,"888,5","888,5",888,NaN,"20,1","19,2","20,2","20,1","19,2","19,1",94,94.0,94,357,"3,4","1,2",NaN
6849,2020/10/12,0900 UTC,0,"888,5","888,5","887,8",NaN,"18,6","16,1","19,2","18,1","16,1","15,4",86,80.0,86,336,"1,5",1,NaN
7771,2020/11/19,1900 UTC,0,882,883,882,719,"21,2","18,2","21,3","20,8","18,4","17,7",85,82.0,83,271,"4,1","1,2",NaN
7960,2020/11/27,1600 UTC,0,"888,3","889,1","888,3","3749,1","25,7","14,4","26,2","24,7","16,1","13,8",56,47.0,50,94,"7,8","4,4",NaN
6752,2020/10/08,0800 UTC,0,887,887,"886,5",NaN,21,"7,2","21,8","20,2","8,2","6,3",45,37.0,41,312,"1,8",",7",NaN
4150,2020/06/21,2200 UTC,0,"890,5","890,5","890,2",NaN,"20,2",9,"21,6","20,1","9,1","7,3",49,40.0,49,110,"4,4","2,3",NaN
7504,2020/11/08,1600 UTC,0,"888,4","889,2","888,4","3861,4","29,1","15,5","29,2","27,5","16,7","14,9",51,43.0,44,89,"7,3","3,2",NaN
4870,2020/07/21,2200 UTC,0,"888,6","888,6","888,5",NaN,"20,5","9,4","22,4","19,9","9,4","8,9",50,42.0,49,36,"3,9","1,3",NaN
1482,2020/03/02,1800 UTC,",8","883,7","884,2","883,6","1660,3",22,"19,9","25,5","21,7","21,1","18,6",87,72.0,87,309,"7,2","1,9",NaN
3806,2020/06/07,1400 UTC,0,"892,6",893,"892,6","2406,8","22,2","14,6","22,6","21,2","15,8","14,6",69,62.0,62,86,"5,5","2,6",NaN
4514,2020/07/07,0200 UTC,0,"889,7","889,8","889,6",NaN,"17,6","9,7",18,"17,4","10,1","9,6",61,59.0,60,102,"4,3","2,2",NaN
1619,2020/03/08,1100 UTC,0,"886,8","886,8","885,8","684,3","20,5","19,4","20,5","18,3","19,6","17,7",96,93.0,93,84,"2,4","1,2",NaN
2196,2020/04/01,1200 UTC,0,"888,4","888,4","887,8","1678,6","24,2","16,5","24,3","22,8","16,9","15,9",69,61.0,62,51,"5,6","2,7",NaN
1697,2020/03/11,1700 UTC,0,"885,4","886,5","885,4","2190,2","25,8","16,7","26,7","24,8","18,3","16,5",64,56.0,57,69,"6,5","2,3",NaN
4943,2020/07/24,2300 UTC,0,"890,2","890,2","889,3",NaN,"19,2","10,2","20,6",17,"10,6","9,4",64,49.0,56,110,"3,2",2,NaN
5906,2020/09/03,0200 UTC,0,"889,1","889,1","888,9",NaN,"20,1","6,5","20,9",20,"6,6","6,2",41,39.0,41,88,"7,4","3,2",NaN
7367,2020/11/02,2300 UTC,",2","883,1","883,1","882,7",NaN,"19,4","18,4","19,6","19,2","18,6","18,1",94,93.0,94,42,"5,6","1,7",NaN
6169,2020/09/14,0100 UTC,0,"890,5","890,5","890,1",NaN,"22,3","7,4","22,9","22,2","7,4","5,6",38,33.0,38,57,6,"2,2",NaN
5983,2020/09/06,0700 UTC,0,888,"888,4","887,9",NaN,"19,2","6,3","19,7","19,1","6,3",6,43,41.0,43,104,"5,4","2,8",NaN
8588,2020/12/23,2000 UTC,0,"882,7","882,9","882,7","1609,8","24,8",17,"26,8","24,6","18,3","16,7",65,56.0,62,333,6,"2,7",NaN

In [17]:
f_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'] = df_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].replace(',', '.', regex=True)

C:\Users\annea\AppData\Local\Temp\ipykernel_9288\3308982152.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'] = df_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].replace(',', '.', regex=True)

In [18]:
df_amostra['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'] = df_amostra['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].replace(',', '.', regex=True)

In [19]:
df_amostra.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
1562,2020/03/06,0200 UTC,0,"888,5","888,5",888,NaN,"20,1","19,2","20,2","20,1","19,2","19,1",94,94.0,94,357,"3,4","1,2",NaN
6849,2020/10/12,0900 UTC,0,"888,5","888,5","887,8",NaN,"18,6","16,1","19,2","18,1","16,1","15,4",86,80.0,86,336,"1,5",1,NaN
7771,2020/11/19,1900 UTC,0,882,883,882,719,"21,2","18,2","21,3","20,8","18,4","17,7",85,82.0,83,271,"4,1","1,2",NaN
7960,2020/11/27,1600 UTC,0,"888,3","889,1","888,3","3749,1","25,7","14,4","26,2","24,7","16,1","13,8",56,47.0,50,94,"7,8","4,4",NaN
6752,2020/10/08,0800 UTC,0,887,887,"886,5",NaN,21,"7,2","21,8","20,2","8,2","6,3",45,37.0,41,312,"1,8",",7",NaN

In [20]:
df_amostra.dtypes

Data                                                      object
Hora UTC                                                  object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                          object
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     object
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           object
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          object
RADIACAO GLOBAL (Kj/m²)                                   object
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)              object
TEMPERATURA DO PONTO DE ORVALHO (°C)                      object
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)          object
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)          object
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                   int64
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 float64
UMIDADE RELATIVA DO AR, HORARIA (%)                        int64
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                       int64
VENTO, RAJADA MAXIMA (m/s)                                object
VENTO, VELOCIDADE HORARIA (m/s)                           object
Unnamed: 19                                              float64
dtype: object

In [21]:
f_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'] = pd.to_numeric(df_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'], errors='coerce')

C:\Users\annea\AppData\Local\Temp\ipykernel_9288\3696780953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'] = pd.to_numeric(df_amostra['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'], errors='coerce')

In [22]:
df_amostra['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'] = pd.to_numeric(df_amostra['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'], errors='coerce')

In [23]:
df_amostra['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'] = pd.to_numeric(df_amostra['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'], errors='coerce')

In [24]:
df_amostra.dtypes

Data                                                      object
Hora UTC                                                  object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                         float64
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     object
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           object
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          object
RADIACAO GLOBAL (Kj/m²)                                   object
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)              object
TEMPERATURA DO PONTO DE ORVALHO (°C)                      object
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)          object
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)          object
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                   int64
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 float64
UMIDADE RELATIVA DO AR, HORARIA (%)                        int64
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                       int64
VENTO, RAJADA MAXIMA (m/s)                                object
VENTO, VELOCIDADE HORARIA (m/s)                           object
Unnamed: 19                                              float64
dtype: object

In [25]:
df_amostra.head(20)

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
1562,2020/03/06,0200 UTC,0.0,"888,5","888,5",888,NaN,"20,1","19,2","20,2","20,1","19,2","19,1",94,94.0,94,357,"3,4","1,2",NaN
6849,2020/10/12,0900 UTC,0.0,"888,5","888,5","887,8",NaN,"18,6","16,1","19,2","18,1","16,1","15,4",86,80.0,86,336,"1,5",1,NaN
7771,2020/11/19,1900 UTC,0.0,882,883,882,719,"21,2","18,2","21,3","20,8","18,4","17,7",85,82.0,83,271,"4,1","1,2",NaN
7960,2020/11/27,1600 UTC,0.0,"888,3","889,1","888,3","3749,1","25,7","14,4","26,2","24,7","16,1","13,8",56,47.0,50,94,"7,8","4,4",NaN
6752,2020/10/08,0800 UTC,0.0,887,887,"886,5",NaN,21,"7,2","21,8","20,2","8,2","6,3",45,37.0,41,312,"1,8",",7",NaN
4150,2020/06/21,2200 UTC,0.0,"890,5","890,5","890,2",NaN,"20,2",9,"21,6","20,1","9,1","7,3",49,40.0,49,110,"4,4","2,3",NaN
7504,2020/11/08,1600 UTC,0.0,"888,4","889,2","888,4","3861,4","29,1","15,5","29,2","27,5","16,7","14,9",51,43.0,44,89,"7,3","3,2",NaN
4870,2020/07/21,2200 UTC,0.0,"888,6","888,6","888,5",NaN,"20,5","9,4","22,4","19,9","9,4","8,9",50,42.0,49,36,"3,9","1,3",NaN
1482,2020/03/02,1800 UTC,0.8,"883,7","884,2","883,6","1660,3",22,"19,9","25,5","21,7","21,1","18,6",87,72.0,87,309,"7,2","1,9",NaN
3806,2020/06/07,1400 UTC,0.0,"892,6",893,"892,6","2406,8","22,2","14,6","22,6","21,2","15,8","14,6",69,62.0,62,86,"5,5","2,6",NaN
4514,2020/07/07,0200 UTC,0.0,"889,7","889,8","889,6",NaN,"17,6","9,7",18,"17,4","10,1","9,6",61,59.0,60,102,"4,3","2,2",NaN
1619,2020/03/08,1100 UTC,0.0,"886,8","886,8","885,8","684,3","20,5","19,4","20,5","18,3","19,6","17,7",96,93.0,93,84,"2,4","1,2",NaN
2196,2020/04/01,1200 UTC,0.0,"888,4","888,4","887,8","1678,6","24,2","16,5","24,3","22,8","16,9","15,9",69,61.0,62,51,"5,6","2,7",NaN
1697,2020/03/11,1700 UTC,0.0,"885,4","886,5","885,4","2190,2","25,8","16,7","26,7","24,8","18,3","16,5",64,56.0,57,69,"6,5","2,3",NaN
4943,2020/07/24,2300 UTC,0.0,"890,2","890,2","889,3",NaN,"19,2","10,2","20,6",17,"10,6","9,4",64,49.0,56,110,"3,2",2,NaN
5906,2020/09/03,0200 UTC,0.0,"889,1","889,1","888,9",NaN,"20,1","6,5","20,9",20,"6,6","6,2",41,39.0,41,88,"7,4","3,2",NaN
7367,2020/11/02,2300 UTC,0.2,"883,1","883,1","882,7",NaN,"19,4","18,4","19,6","19,2","18,6","18,1",94,93.0,94,42,"5,6","1,7",NaN
6169,2020/09/14,0100 UTC,0.0,"890,5","890,5","890,1",NaN,"22,3","7,4","22,9","22,2","7,4","5,6",38,33.0,38,57,6,"2,2",NaN
5983,2020/09/06,0700 UTC,0.0,888,"888,4","887,9",NaN,"19,2","6,3","19,7","19,1","6,3",6,43,41.0,43,104,"5,4","2,8",NaN
8588,2020/12/23,2000 UTC,0.0,"882,7","882,9","882,7","1609,8","24,8",17,"26,8","24,6","18,3","16,7",65,56.0,62,333,6,"2,7",NaN

In [28]:
df_amostra.describe()

,UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))",Unnamed: 19
count,20.00000,20.000000,20.000000,20.000000,0.0
mean,71.15000,63.950000,68.050000,166.000000,NaN
std,16.10255,17.479236,17.658977,96.435962,NaN
min,40.00000,32.000000,33.000000,41.000000,NaN
25%,62.75000,53.500000,55.000000,98.750000,NaN
50%,74.50000,63.000000,72.000000,130.000000,NaN
75%,82.75000,78.250000,81.750000,231.500000,NaN
max,95.00000,95.000000,95.000000,348.000000,NaN

In [29]:
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}

df_data = pd.DataFrame(data)

In [30]:
df_data['A+B'] = df_data['A'] * df_data['B']

In [31]:

df_data.head()

   A  B  C  A+B
0  1  4  7    4
1  2  5  8   10
2  3  6  9   18