In [6]:
import pandas as pd

df = pd.read_csv('brasilia.csv', delimiter=';', skiprows=8, encoding='latin1')

In [7]:
df.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2020/01/01,0000 UTC,0,"884,1","884,2","883,9",NaN,20,"18,1","20,2","19,6","18,4","17,7",89,88.0,89,108,"2,7",",8",NaN
1,2020/01/01,0100 UTC,0,885,885,"884,1",NaN,"19,5","18,1",20,"19,4","18,4","17,8",91,89.0,91,272,"1,4",",3",NaN
2,2020/01/01,0200 UTC,0,"885,5","885,5",885,NaN,20,"18,8","20,1","19,4","18,9","18,1",94,91.0,93,40,"1,5","1,1",NaN
3,2020/01/01,0300 UTC,0,"885,3","885,5","885,3",NaN,"19,5","17,9","20,2","19,4",19,"17,8",93,90.0,91,319,"2,6",1,NaN
4,2020/01/01,0400 UTC,0,"885,2","885,4","885,2",NaN,"19,5","17,3","19,8","19,3","18,2","17,3",92,87.0,87,321,"2,7","1,4",NaN

In [9]:
df.tail()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
8779,2020/12/31,1900 UTC,0,"885,2","885,8","885,1",1005,"28,1","15,1","29,3",28,"16,2","14,4",48,42.0,45,165,"5,7","2,2",NaN
8780,2020/12/31,2000 UTC,0,"885,4","885,5","885,1",313,"23,6","14,8","28,1","23,5","16,4","14,1",59,44.0,58,332,"7,7","3,5",NaN
8781,2020/12/31,2100 UTC,0,"885,6","885,6","885,1","292,2","23,6","17,2","23,6","22,6","17,2","14,9",69,58.0,67,322,"7,7","1,1",NaN
8782,2020/12/31,2200 UTC,0,"886,1","886,1","885,6","123,2","22,3","16,8","23,6","22,3","17,1","15,6",71,63.0,71,309,"5,5","1,6",NaN
8783,2020/12/31,2300 UTC,0,"886,3","886,3",886,NaN,"21,3","16,4","22,3","21,2","16,8","15,7",76,68.0,74,169,"3,9",",7",NaN

In [11]:
df.shape

(8784, 20)

In [12]:
df.describe()

,UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))",Unnamed: 19
count,8784.000000,8783.000000,8784.000000,8784.000000,0.0
mean,70.122382,64.052602,67.105191,148.566143,NaN
std,21.209627,22.059163,21.735581,101.899887,NaN
min,12.000000,10.000000,10.000000,1.000000,NaN
25%,54.000000,46.000000,50.000000,80.000000,NaN
50%,74.000000,66.000000,70.000000,108.000000,NaN
75%,90.000000,84.000000,87.000000,220.000000,NaN
max,97.000000,97.000000,97.000000,360.000000,NaN

In [13]:
print(df.describe())

       UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)  \
count                               8784.000000
mean                                  70.122382
std                                   21.209627
min                                   12.000000
25%                                   54.000000
50%                                   74.000000
75%                                   90.000000
max                                   97.000000

       UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)  \
count                               8783.000000
mean                                  64.052602
std                                   22.059163
min                                   10.000000
25%                                   46.000000
50%                                   66.000000
75%                                   84.000000
max                                   97.000000

       UMIDADE RELATIVA DO AR, HORARIA (%)  \
count                          8784.000000
mean                             67.105191
std                              21.735581
min                              10.000000
25%                              50.000000
50%                              70.000000
75%                              87.000000
max                              97.000000

       VENTO, DIREÇÃO HORARIA (gr) (° (gr))  Unnamed: 19
count                           8784.000000          0.0
mean                             148.566143          NaN
std                              101.899887          NaN
min                                1.000000          NaN
25%                               80.000000          NaN
50%                              108.000000          NaN
75%                              220.000000          NaN
max                              360.000000          NaN

In [14]:
#mostra o tipo de dados
df.dtypes

Data                                                      object
Hora UTC                                                  object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                          object
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     object
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           object
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          object
RADIACAO GLOBAL (Kj/m²)                                   object
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)              object
TEMPERATURA DO PONTO DE ORVALHO (°C)                      object
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)          object
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)          object
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                   int64
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 float64
UMIDADE RELATIVA DO AR, HORARIA (%)                        int64
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                       int64
VENTO, RAJADA MAXIMA (m/s)                                object
VENTO, VELOCIDADE HORARIA (m/s)                           object
Unnamed: 19                                              float64
dtype: object

In [16]:
df.sample(n=5)

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
4090,2020/06/19,1000 UTC,0,"891,1","891,1","890,8","2,6","14,4","11,8","14,4",14,"12,1","11,8",88,84.0,84,105,"6,5","3,3",NaN
1903,2020/03/20,0700 UTC,0,"883,9","884,4","883,7",NaN,"18,3","17,4",19,"18,3","18,2","17,4",95,94.0,94,262,"3,4","1,1",NaN
984,2020/02/11,0000 UTC,0,"888,6","888,6","887,9",NaN,"19,1","17,3","20,4",19,"17,3","16,6",89,79.0,89,27,"3,3",",8",NaN
133,2020/01/06,1300 UTC,0,887,"887,1","886,6","2154,5","21,3","17,7","22,2","21,2","18,3","17,2",81,77.0,80,308,"12,6","5,1",NaN
7325,2020/11/01,0500 UTC,0,"884,3",885,"884,3",NaN,"18,3","17,3","18,6","18,3","17,3",17,94,91.0,94,329,"3,9","1,6",NaN

In [39]:
df_reduzido = df[['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)','UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)']]

In [40]:
df_reduzido.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)",UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
0,2020/01/01,0000 UTC,0,88.0
1,2020/01/01,0100 UTC,0,89.0
2,2020/01/01,0200 UTC,0,91.0
3,2020/01/01,0300 UTC,0,90.0
4,2020/01/01,0400 UTC,0,87.0

In [42]:
df.columns

Index(['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)',
       'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
       'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)',
       'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)',
       'RADIACAO GLOBAL (Kj/m²)',
       'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
       'TEMPERATURA DO PONTO DE ORVALHO (°C)',
       'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)',
       'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)',
       'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)',
       'UMIDADE RELATIVA DO AR, HORARIA (%)',
       'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)',
       'VENTO, VELOCIDADE HORARIA (m/s)', 'Unnamed: 19'],
      dtype='object')

In [38]:
coluna_data = df['Data']

In [44]:
coluna_data.head()

0    2020/01/01
1    2020/01/01
2    2020/01/01
3    2020/01/01
4    2020/01/01
Name: Data, dtype: object

In [45]:
coluna_data.min()

'2020/01/01'

In [46]:
coluna_umidade_minima = df['UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)']

In [47]:
coluna_umidade_minima.min()

np.float64(10.0)

In [48]:
coluna_umidade_minima.max()

np.float64(97.0)

In [50]:
coluna_umidade_minima.sum()

np.float64(562574.0)

In [51]:
coluna_umidade_minima.mean()

np.float64(64.05260161675965)

In [52]:
df.isnull()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8780,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8781,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8782,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8783,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True

In [54]:
nulos_por_coluna = df.isnull().sum()
print(nulos_por_coluna)

Data                                                        0
Hora UTC                                                    0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                            0
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)       0
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)             0
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)            0
RADIACAO GLOBAL (Kj/m²)                                  4036
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)                0
TEMPERATURA DO PONTO DE ORVALHO (°C)                        0
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                  0
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                  0
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)            0
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)            0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                    0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                    1
UMIDADE RELATIVA DO AR, HORARIA (%)                         0
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                        0
VENTO, RAJADA MAXIMA (m/s)                                  0
VENTO, VELOCIDADE HORARIA (m/s)                             0
Unnamed: 19                                              8784
dtype: int64

In [56]:
df.dropna()

Empty DataFrame
Columns: [Data, Hora UTC, PRECIPITAÇÃO TOTAL, HORÁRIO (mm), PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB), PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB), PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB), RADIACAO GLOBAL (Kj/m²), TEMPERATURA DO AR - BULBO SECO, HORARIA (°C), TEMPERATURA DO PONTO DE ORVALHO (°C), TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C), TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C), TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C), TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C), UMIDADE REL. MAX. NA HORA ANT. (AUT) (%), UMIDADE REL. MIN. NA HORA ANT. (AUT) (%), UMIDADE RELATIVA DO AR, HORARIA (%), VENTO, DIREÇÃO HORARIA (gr) (° (gr)), VENTO, RAJADA MAXIMA (m/s), VENTO, VELOCIDADE HORARIA (m/s), Unnamed: 19]
Index: []

In [59]:
remover = df.dropna(axis=0, how='all')
remover

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2020/01/01,0000 UTC,0,"884,1","884,2","883,9",NaN,20,"18,1","20,2","19,6","18,4","17,7",89,88.0,89,108,"2,7",",8",NaN
1,2020/01/01,0100 UTC,0,885,885,"884,1",NaN,"19,5","18,1",20,"19,4","18,4","17,8",91,89.0,91,272,"1,4",",3",NaN
2,2020/01/01,0200 UTC,0,"885,5","885,5",885,NaN,20,"18,8","20,1","19,4","18,9","18,1",94,91.0,93,40,"1,5","1,1",NaN
3,2020/01/01,0300 UTC,0,"885,3","885,5","885,3",NaN,"19,5","17,9","20,2","19,4",19,"17,8",93,90.0,91,319,"2,6",1,NaN
4,2020/01/01,0400 UTC,0,"885,2","885,4","885,2",NaN,"19,5","17,3","19,8","19,3","18,2","17,3",92,87.0,87,321,"2,7","1,4",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2020/12/31,1900 UTC,0,"885,2","885,8","885,1",1005,"28,1","15,1","29,3",28,"16,2","14,4",48,42.0,45,165,"5,7","2,2",NaN
8780,2020/12/31,2000 UTC,0,"885,4","885,5","885,1",313,"23,6","14,8","28,1","23,5","16,4","14,1",59,44.0,58,332,"7,7","3,5",NaN
8781,2020/12/31,2100 UTC,0,"885,6","885,6","885,1","292,2","23,6","17,2","23,6","22,6","17,2","14,9",69,58.0,67,322,"7,7","1,1",NaN
8782,2020/12/31,2200 UTC,0,"886,1","886,1","885,6","123,2","22,3","16,8","23,6","22,3","17,1","15,6",71,63.0,71,309,"5,5","1,6",NaN
8783,2020/12/31,2300 UTC,0,"886,3","886,3",886,NaN,"21,3","16,4","22,3","21,2","16,8","15,7",76,68.0,74,169,"3,9",",7",NaN

In [65]:
df_substituido = df.replace('0', '-1')

df_substituido.head(9)

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2020/01/01,0000 UTC,-1,"884,1","884,2","883,9",NaN,20,"18,1","20,2","19,6","18,4","17,7",89,88.0,89,108,"2,7",",8",NaN
1,2020/01/01,0100 UTC,-1,885,885,"884,1",NaN,"19,5","18,1",20,"19,4","18,4","17,8",91,89.0,91,272,"1,4",",3",NaN
2,2020/01/01,0200 UTC,-1,"885,5","885,5",885,NaN,20,"18,8","20,1","19,4","18,9","18,1",94,91.0,93,40,"1,5","1,1",NaN
3,2020/01/01,0300 UTC,-1,"885,3","885,5","885,3",NaN,"19,5","17,9","20,2","19,4",19,"17,8",93,90.0,91,319,"2,6",1,NaN
4,2020/01/01,0400 UTC,-1,"885,2","885,4","885,2",NaN,"19,5","17,3","19,8","19,3","18,2","17,3",92,87.0,87,321,"2,7","1,4",NaN
5,2020/01/01,0500 UTC,-1,"884,5","885,2","884,5",NaN,"18,9","17,1","19,6","18,7","17,3","16,9",90,86.0,89,277,"2,6","1,3",NaN
6,2020/01/01,0600 UTC,-1,"884,5","884,6","884,4",NaN,"19,1","17,3","19,1","18,8","17,6","17,2",91,89.0,89,330,2,"1,4",NaN
7,2020/01/01,0700 UTC,-1,"884,4","884,6","884,4",NaN,"19,4","16,5","19,6","19,1","17,3","16,5",89,82.0,83,346,"2,8","1,8",NaN
8,2020/01/01,0800 UTC,",2","884,7","884,7","884,4",NaN,"19,2","16,6","19,8","19,2","16,6","16,2",85,80.0,85,14,"2,7","1,6",NaN

In [66]:
df['Coluna1_normalizada'] = (df['UMIDADE RELATIVA DO AR, HORARIA (%)'] - df['UMIDADE RELATIVA DO AR, HORARIA (%)'].min()) / (df['UMIDADE RELATIVA DO AR, HORARIA (%)'].max() - df['UMIDADE RELATIVA DO AR, HORARIA (%)'].min())

In [67]:
df['Coluna1_normalizada'].head(20)

0     0.908046
1     0.931034
2     0.954023
3     0.931034
4     0.885057
5     0.908046
6     0.908046
7     0.839080
8     0.862069
9     0.885057
10    0.850575
11    0.862069
12    0.804598
13    0.712644
14    0.793103
15    0.839080
16    0.655172
17    0.643678
18    0.873563
19    0.735632
Name: Coluna1_normalizada, dtype: float64

In [2]:
import matplotlib.pyplot as plt